// image
let
    ai = 'application/postscript',
    bmp = 'image/bmp',
    dib = 'image/bmp',
    drw = 'application/drafting',
    gif = 'image/gif',
    hdr = 'image/vnd.radiance',
    ico = 'image/icon',
    jfif = 'image/pipeg',
    jpeg = 'image/jpeg',
    jpg = 'image/jpeg',
    pct = 'image/pict',
    pic = 'image/pict',
    pjp = 'image/jpeg', // 'image/pjpeg',
    pjpeg = 'image/jpeg', // 'image/pjpeg',
    png = 'image/png',
    pnm = '',
    psd = 'image/photoshop',
    psp = 'image/psp',
    raw = '',
    svg = 'image/svg+xml',
    svgz = 'image/svg+xml',
    tga = 'image/tga',
    tif = 'image/tiff',
    tiff = 'image/tiff',
    tpic = 'image/tga',
    vda = 'image/tga',
    vst = 'image/tga',
    webp = 'image/webp',
    xbm = 'image/xbm',
    xcf = 'image/xcf';

// audio
let
    aac = 'audio/aac',
    aif = 'audio/x-aiff',
    aiff = 'audio/x-aiff',
    amr = 'audio/amr',
    au = 'audio/basic',
    flac = 'audio/flac',
    iff = '',
    m4a = 'audio/aac',
    m4b = 'audio/m4b',
    mid = 'audio/mid',
    midi = 'audio/mid',
    mp3 = 'audio/mpeg',
    mpa = 'audio/mpeg',
    mpc = 'application/x-project',
    oga = 'audio/ogg',
    ogg = 'application/ogg',
    opus = 'audio/opus',
    ra = 'audio/x-realaudio',
    ram = 'audio/x-pn-realaudio',
    snd = 'audio/basic',
    wav = 'audio/wav',
    weba = 'audio/webm',
    wma = 'audio/x-ms-wma';

// video
let
    asx = 'video/x-ms-asf',
    avi = 'video/x-msvideo',
    divx = 'video/divx',
    flv = 'video/x-flv',
    m4v = 'video/mp4',
    mkv = 'video/x-matroska',
    mov = 'video/quicktime',
    mp4 = 'video/mp4',
    mpeg = 'video/mpeg',
    mpg = 'video/mpeg',
    ogm = 'video/ogg',
    ogv = 'video/ogg',
    ogx = 'application/ogg',
    rm = 'application/vnd.rn-realmedia',
    rmvb = 'application/vnd.rn-realmedia-vbr',
    smil = 'application/smil',
    webm = 'video/webm',
    wmv = 'video/x-ms-wmv',
    xvid = 'video/x-xvid';

    // model
let 
    _3d,
    _3ds,
    _3mf,
    _ac,
    ac3d,
    acc,
    amf
    amj,
    ase,
    ask,
    b3d,
    blend,
    bvh,
    cob,
    dae,//collada,
    dxf,
    enff,
    fbx
    gltf,
    'ifc-step',
    irr,
    lwo,
    lws,
    lxo,
    md2,
    md3,
    md5,
    mdc,
    mdl,
    mesh, //mesh_xml,
    mot,
    ms3d,
    ndo,
    nff,
    obj,
    off,
    ogex,
    ply,
    pmx,
    prj,
    q3o,
    q3s,
    raw,
    scn,
    sib,
    smd,
    stl,
    ter,
    uc,
    vta,
    x,
    x3d,
    xgl,
    zgl;

export const fileTypes = {
    chrome: {
        // image
        tiff,
        pjp,
        pjpeg,
        jfif,
        tif,
        gif,
        svg,
        bmp,
        png,
        jpeg,
        svgz,
        jpg,
        webp,
        ico,
        xbm,
        dib,

        // audio
        opus,
        flac,
        weba,
        wav,
        ogg,
        m4a,
        mp3,
        oga,
        mid,
        amr,
        aiff,
        wma,
        au,
        aac,

        // video
        ogm,
        wmv,
        mpg,
        webm,
        ogv,
        mov,
        asx,
        mpeg,
        mp4,
        m4v,
        avi,

    },
    firefox: {
        // image
        jpe,
        jpg,
        jpeg,
        gif,
        png,
        bmp,
        ico,
        svg,
        svgz,
        tif,
        tiff,
        ai,
        drw,
        pct,
        psp,
        xcf,
        psd,
        raw,

        // audio
        aac,
        aif,
        flac,
        iff,
        m4a,
        m4b,
        mid,
        midi,
        mp3,
        mpa,
        mpc,
        oga,
        ogg,
        ra,
        ram,
        snd,
        wav,
        wma,

        // video
        avi,
        divx,
        flv,
        m4v,
        mkv,
        mov,
        mp4,
        mpeg,
        mpg,
        ogm,
        ogv,
        ogx,
        rm,
        rmvb,
        smil,
        webm,
        wmv,
        xvid
    },

    // document
    document: {

    },

    unity: {
        // model
        _3d,
        _3ds,

    }
};